---
apiVersion: v1
kind: Service
metadata:
  name: ms-notification-reactive
spec:
  type: ClusterIP
  selector:
    app: ms-notification-reactive
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080